--- 
framework: 
  AdminMode: 0
  ApplicationClass: App::Changeloggr
  ApplicationName: Changelogger
  ApplicationUUID: DFE97C64-0462-11DE-B67F-355F32960180
  ConfigFileVersion: 4
  Database: 
    AutoUpgrade: 1
    CheckSchema: 1
    Database: app_changeloggr
    Driver: SQLite
    Host: localhost
    Password: ''
    RecordBaseClass: Jifty::DBI::Record::Cachable
    User: ''
    Version: 0.0.9
  DevelMode: 1
  L10N: 
    PoDir: share/po
  LogLevel: INFO
  Mailer: Sendmail
  MailerArgs: []
  PubSub:
    Backend: Memcached
    Enable: 1
  Plugins: 
    - SkeletonApp: {}
    - REST: {}
    - ErrorTemplates: {}
    - CompressedCSSandJS: {}
    - AdminUI: {}
    - Feedback:
        to:   changelogger@bestpractical.com
        from: changelogger-user@bestpractical.com
  SkipAccessControl: 0
  TemplateClass: App::Changeloggr::View
  View: 
    Handlers: 
      - Jifty::View::Static::Handler
      - Jifty::View::Declare::Handler
      - Jifty::View::Mason::Handler
  Web: 
    BaseURL: http://localhost
    Port: 8888
    ServerClass: Jifty::Server::Prefork
    ServeStaticFiles: 1
    StaticRoot: share/web/static
    TemplateRoot: share/web/templates
application:
  BackgroundImport: 1

